# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  aarch64: "ghcr.io/hassio-addons/base/aarch64:20.0.1"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  amd64: "ghcr.io/hassio-addons/base/amd64:20.0.1"
  
args:
  BUILD_REPO: litinoveweedle/hassio-addons-dev
  BUILD_DESCRIPTION: "hassio taptap addon"
  # renovate: datasource=github-releases depName=taptap packageName=litinoveweedle/taptap versioning=semver
  TAPTAP_VERSION: "0.2.6"
  # renovate: datasource=github-releases depName=taptap-mqtt packageName=litinoveweedle/taptap-mqtt versioning=semver
  TAPTAP_MQTT_VERSION: "0.2.4"
