# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  aarch64: "ghcr.io/hassio-addons/base/aarch64:18.2.1"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  amd64: "ghcr.io/hassio-addons/base/amd64:18.2.1"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  armhf: "ghcr.io/hassio-addons/base/armhf:18.2.1"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  armv7: "ghcr.io/hassio-addons/base/armv7:18.2.1"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  i386: "ghcr.io/hassio-addons/base/i386:18.2.1"
  
args:
  BUILD_REPO: litinoveweedle/hassio-addons-dev
  BUILD_DESCRIPTION: "hassio taptap addon"
  # renovate: datasource=github-releases depName=taptap packageName=litinoveweedle/taptap versioning=semver
  TAPTAP_VERSION: "0.2.5"
  # renovate: datasource=github-releases depName=taptap-mqtt packageName=litinoveweedle/taptap-mqtt versioning=semver
  TAPTAP_MQTT_VERSION: "0.1.0"
