# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TapTap
version: "dev"
slug: taptap
description: Tigo CCA to HomeAssistant MQTT bridge
url: "https://github.com/litinoveweedle/hassio-addons/tree/main/taptap"
image: "ghcr.io/litinoveweedle/hassio-addon-taptap-{arch}"
homeassistant: 2025.3.1
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
uart: true
usb: true
options:
  log_level: info
  mqtt_server: null
  mqtt_port: 1883
  mqtt_qos: 1
  mqtt_timeout: 5
  mqtt_user: null
  mqtt_pass: null
  taptap_port: 502
  taptap_topic_name: tigo
  taptap_modules_serials: null
  taptap_topic_prefix: taptap
  taptap_update: 10
  taptap_timeout: 120
  ha_entity_availability: true
  ha_discovery_prefix: homeassistant
  ha_birth_topic: homeassistant/status
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  mqtt_server: str
  mqtt_port: port
  mqtt_qos: int(0,2)
  mqtt_timeout: int(1,10)
  mqtt_user: str
  mqtt_pass: password
  taptap_serial: device(subsystem=tty)?
  taptap_address: str
  taptap_port: port
  taptap_topic_name: match(^\w+$)
  taptap_modules_serials:
    - match(^\w+\s*\:\s*[0-9A-Z]\-[0-9A-Z]{7}$)
  taptap_topic_prefix: match((\w+)(\/\w+)*)
  taptap_update: int
  taptap_timeout: int
  ha_entity_availability: bool
  ha_discovery_prefix: str
  ha_birth_topic: str
