name: Builder

env:
  MONITORED_FILES: 'config.json config.yaml config.yml Dockerfile rootfs'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_addons: ${{ steps.filter.outputs.changed_addons }}
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v47.0.6

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Filter changed add-ons
        id: filter
        env:
          ADDONS: ${{ steps.addons.outputs.addons }}
          CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
        run: |
          declare -a changed_addons

          # If workflow file changed, build all addons
          if [[ "${CHANGED_FILES}" =~ \.github/workflows/(builder|build-addon)\.yaml ]]; then
            changed_addons=(${ADDONS})
          # Otherwise, check which addons have changed files
          else
            for addon in ${ADDONS}; do
              for file in ${MONITORED_FILES}; do
                if [[ "${CHANGED_FILES}" =~ ${addon}/${file} ]]; then
                  changed_addons+=("${addon}")
                  break
                fi
              done
            done
          fi
          
          if [[ ${#changed_addons[@]} -gt 0 ]]; then
            echo "Changed add-ons: ${changed_addons[@]}"
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_addons=$(jq -nc '$ARGS.positional' --args "${changed_addons[@]}")" >> "$GITHUB_OUTPUT"
          else
            echo "No add-on had any monitored files changed"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: Build ${{ matrix.addon }}
    needs: init
    if: needs.init.outputs.changed == 'true'
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        addon: ${{ fromJSON(needs.init.outputs.changed_addons) }}
    uses: ./.github/workflows/build-addon.yaml
    with:
      addon: ${{ matrix.addon }}
      version: dev
      publish: false
      release: false
    secrets: inherit
